Mutex ${MUTEX}

RemoteIPHeader ${REMOTEIP_HEADER}
RemoteIPInternalProxy ${REMOTEIP_INT_PROXY}

RequestHeader set X-Forwarded-Proto "${REQ_HEADER_FORWARDED_PROTO}"
RequestHeader set X-Real-IP %{REMOTE_ADDR}s
RequestHeader set X-Unique-ID %{UNIQUE_ID}e

ServerName ${SERVER_NAME}
ServerAdmin ${SERVER_ADMIN}

UseCanonicalName on

<VirtualHost *:${PORT}>
    Protocols ${H2_PROTOCOLS}
    H2Direct ${H2_DIRECT}
    DocumentRoot /usr/local/apache2/htdocs
    DirectoryIndex index.html
    <Directory "/usr/local/apache2/htdocs">
        Options None
        AllowOverride None
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost *:${SSL_PORT}>
    Protocols ${H2_PROTOCOLS}
    H2Direct ${H2_DIRECT}
    SSLEngine ${SSL_ENGINE}
    SSLCertificateFile ${SSL_CERT_FILE}
    SSLCertificateKeyFile ${SSL_CERT_KEY_FILE}
    DocumentRoot /usr/local/apache2/htdocs
    DirectoryIndex index.html
    <Directory "/usr/local/apache2/htdocs">
        Options None
        AllowOverride None
        Require all granted
    </Directory>
</VirtualHost>
