ServerTokens Full
SecServerSignature "Microsoft-IIS/10.0"
Header always set X-Powered-By "ASP.NET"
Header always set X-AspNet-Version "4.0.30319"
Header always unset Upgrade

ErrorDocument 403 "<html><head><title>403 - Forbidden</title></head><body><h2>403 - Forbidden: Access is denied.</h2><h3>You do not have permission to view this directory or page.</h3></body></html>"
ErrorDocument 404 "<html><head><title>404 - Not Found</title></head><body><h2>404 - Not Found</h2><h3>The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.</h3></body></html>"
