ServerTokens Full
SecServerSignature "nginx/1.24.0"
Header always unset Server
Header always set Server "nginx/1.24.0"
Header always set X-Powered-By "PHP/8.2.15"
Header always unset Upgrade

ErrorDocument 403 "<html><head><title>403 Forbidden</title></head><body><center><h1>403 Forbidden</h1></center><hr><center>nginx/1.24.0</center></body></html>"
ErrorDocument 404 "<html><head><title>404 Not Found</title></head><body><center><h1>404 Not Found</h1></center><hr><center>nginx/1.24.0</center></body></html>"
