input {
  beats {
    port => 5044
  }
}

filter {
  json {
    source => "message"
  }
}

output {
  file {
    path => "/usr/share/logstash/data/honeypot-events-%{+YYYY-MM-dd}.ndjson"
    codec => json_lines
  }
  stdout {
    codec => rubydebug
  }
}
